name: Pre-Merge Checks

on:
  pull_request:
    branches:
      - main

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    needs: run-pre-merge-checks

    steps:
      - name: Check PR title
        shell: bash
        run: |
          if [[ ! "${{ github.event.pull_request.title }}" =~ ^(C4LIFE|release/) ]]; then
            echo "Error: PR title does not start with 'C4LIFE' or 'release/'."
            echo "Please update the PR title to follow the naming convention."
            exit 1
          else
            echo "PR title follows the naming convention."
          fi
        continue-on-error: false

  run-pre-merge-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.2"

      - name: Install Dart dependencies
        run: flutter pub get

      - name: Analyzing code
        id: run-script
        run: |
          chmod +x ./custom_scripts/pre_merge_checks.sh
          ./custom_scripts/pre_merge_checks.sh
        continue-on-error: false

