name: Pre-Merge Checks

on:
  pull_request:
    branches:
      - main

jobs:
  run-pre-merge-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.2"

      - name: Install Dart dependencies
        run: flutter pub get

      - name: Analyzing code
        id: run-script
        run: |
          chmod +x ./custom_scripts/pre_merge_checks.sh
          ./custom_scripts/pre_merge_checks.sh
        continue-on-error: false

  
